---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hello
subjects:
- kind: ServiceAccount
  name: hello