apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: spring-hello
build:
  artifacts:
  - image: public.ecr.aws/kerminator/spring-hello
    jib: {}

# portForward:
#   - resourceType: deployment
#     resourceName: hello
#     port: 8081 #
#     localPort: 8081 # *Optional*

profiles:
  - name: local
    activation:
      - kubeContext: rancher-desktop
    manifests:
      kustomize:
        paths:
          - manifests/overlays/local
  # - name: playground
  #   deploy:
  #     kustomize:
  #       paths: 
  #         - manifests/overlays/dev
  #     kubeContext: playground
