apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: spring-hello
build:
  artifacts:
  - image: kerminator/spring-hello
    jib: {}
deploy:
  kubectl:
    manifests:
    - manifests/deployment.yaml
portForward:
- resourceType: service
  resourceName: hello
  port: 8080 # 
  localPort: 8080 # *Optional*