apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: spring-hello
build:
  artifacts:
  - image: public.ecr.aws/kerminator/spring-hello
    jib: {}
deploy:
  kubectl:
    manifests:
    - manifests/*.yaml
portForward:
- resourceType: service
  resourceName: hello
  port: 8081 #
  localPort: 8081 # *Optional*