apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: spring-hello
build:
  artifacts:
  - image: public.ecr.aws/kerminator/spring-hello
    jib: {}

portForward:
  - resourceType: service
    resourceName: hello
    port: 8081 #
    localPort: 8081 # *Optional*

profiles:
  - name: local
    deploy:
      kustomize:
        paths:
          - manifests/overlays/local
      kubeContext: kind-kind
  - name: playground
    deploy:
      kustomize:
        paths: 
          - manifests/overlays/dev
      kubeContext: playground
