server:
  port: 8081

spring:
  cloud:
    kubernetes:
      reload:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus: 
      enabled: true
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

#logging:
#  level:
#    org.springframework: DEBUG  
    