server:
  shutdown: graceful
  port: 8081

spring:
  application:
    name: hello
  datasource:
    #url: jdbc:h2:file:./foo
    #driverClassName: org.h2.Driver
    #username: sa
    #password: passu
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-ui
  #flyway:
  #  enabled: true
  #  baselineOnMigrate: true
  #  validateOnMigrate: true
    #locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      cluster: local
      # Micrometer Metrics configures this attribute with "unknown value".
      # It should probably be autoconfigured correctly by Spring Boot.
      "service.name": ${spring.application.name}

  otlp:
    tracing:
     endpoint: http://otel-collector:4318/v1/traces

#logging:
# level:
#   org.springframework: DEBUG