server:
  shutdown: graceful
  port: 8081

spring:
  application:
    name: hello

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      cluster: local
      # Micrometer Metrics configures this attribute with "unknown value".
      # It should probably be autoconfigured correctly by Spring Boot.
      "service.name": ${spring.application.name}

  otlp:
    tracing:
      endpoint: http://otel-collector.otel-demo.svc.cluster.local:4318/v1/traces

#logging:
# level:
#   org.springframework: DEBUG