apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: hello
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - configmaps
  - secrets
  - endpoints
  verbs:
  - get
  - list
  - watch