apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
    route: "true"
spec:
  selector:
    app: hello
  type: NodePort
  ports:
    - protocol: TCP 
      port: 8080
      targetPort: 8081