package org.kerminator.hello.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

/**
 * Entity representing a product in the system.
 * Maps to the 'products' table in the database.
 */
@Entity
@Table(name = "products")
public class Product {

    /**
     * Unique identifier for the product.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product.
     * Cannot be null.
     */
    @NotBlank(message = "Product name is required")
    @Size(min = 2, max = 100, message = "Product name must be between 2 and 100 characters")
    @Column(nullable = false)
    private String name;

    /**
     * Description of the product.
     * Limited to 1000 characters.
     */
    @Size(max = 1000, message = "Description cannot exceed 1000 characters")
    @Column(length = 1000)
    private String description;

    /**
     * Price of the product.
     * Cannot be null.
     * Stored with precision of 10 digits and 2 decimal places.
     */
    @NotNull(message = "Price is required")
    @DecimalMin(value = "0.01", message = "Price must be at least 0.01")
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * Available quantity in stock.
     * Stored in the 'stock_quantity' column.
     */
    @Column(name = "stock_quantity")
    private Integer stockQuantity;

    /**
     * Indicates if the product is currently in stock.
     * Stored in the 'in_stock' column.
     */
    @Column(name = "in_stock")
    private Boolean inStock;

    /**
     * Default constructor required by JPA.
     */
    public Product() {
    }

    /**
     * Constructs a product with all fields.
     *
     * @param id            Unique identifier for the product
     * @param name          Name of the product
     * @param description   Description of the product
     * @param price         Price of the product
     * @param stockQuantity Available quantity in stock
     * @param inStock       Indicates if the product is currently in stock
     */
    public Product(Long id, String name, String description, BigDecimal price, Integer stockQuantity, Boolean inStock) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
        this.stockQuantity = stockQuantity;
        this.inStock = inStock;
    }

    /**
     * Gets the product's unique identifier.
     *
     * @return The product ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the product's unique identifier.
     *
     * @param id The product ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the product's name.
     *
     * @return The product name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the product's name.
     *
     * @param name The product name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the product's description.
     *
     * @return The product description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the product's description.
     *
     * @param description The product description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the product's price.
     *
     * @return The product price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the product's price.
     *
     * @param price The product price to set
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Gets the product's stock quantity.
     *
     * @return The product stock quantity
     */
    public Integer getStockQuantity() {
        return stockQuantity;
    }

    /**
     * Sets the product's stock quantity.
     *
     * @param stockQuantity The product stock quantity to set
     */
    public void setStockQuantity(Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    /**
     * Gets whether the product is in stock.
     *
     * @return True if the product is in stock, false otherwise
     */
    public Boolean getInStock() {
        return inStock;
    }

    /**
     * Sets whether the product is in stock.
     *
     * @param inStock True if the product is in stock, false otherwise
     */
    public void setInStock(Boolean inStock) {
        this.inStock = inStock;
    }

}
